### ISSUE TITLE
max_pct_missing not working

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/genutil#1]
running Test/test_stats_missing.py

**Comment by dnadeau4** [comment]
Can you give me more details.

**Comment by doutriaux1** [comment]
did you look at the test?

**Comment by doutriaux1** [comment]
i think there was case where the max_pct missing was set and we were still getting data back and/or vice-versa

**Comment by doutriaux1** [comment]
from the test we might have fixed this already

**Comment by doutriaux1** [comment]
```python
import MV2,numpy,genutil
for m in numpy.arange(0,100.,.25):
       print m, genutil.statistics.std(a,max_pct_missing=m)
```
seems to give the correct results.
