### ISSUE TITLE
genutil's testStatistics failed with numpy 1.15.1

### ISSUE THREAD

**Issue by muryanto1** [CDAT/genutil#26]
testStatistics failed with numpy 1.15.1 for both linux and mac.
https://circleci.com/gh/CDAT/genutil/167
```
======================================================================
FAIL: testStatisitcs (test_genutil_statistics.GENUTIL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/project/tests/test_genutil_statistics.py", line 21, in testStatisitcs
    self.assertArraysEqual(genutil.statistics.laggedcorrelation(u,v,axis=0), f( nm+"_1"))
  File "/home/circleci/project/tests/test_genutil_statistics.py", line 9, in assertArraysEqual
    self.assertTrue(numpy.ma.allclose(A,B))
AssertionError: False is not true
----------------------------------------------------------------------
Ran 1 test in 2.071s
FAILED (failures=1)
FAILED...cmd: ['nosetests', '-s', '/home/circleci/project/tests/test_genutil_statistics.py']
Ran 13 tests, 1 failed (92.31% success)
Failed tests:

`````
When I reran the testcase with numpy=1.14, testStatistics passes.

**Comment by dnadeau4** [comment]
@doutriaux1 do you know why genutil fails on statistics?  Anything to do with you py3 change?

**Comment by doutriaux1** [comment]
@dnadeau4 we looked at it yesterday with @muryanto1 it seems to be nupmy 1.14 to numpy 1.15 related

**Comment by dnadeau4** [comment]
ok I'll look into it.

**Comment by dnadeau4** [comment]
for some reason the values are no longer close in the first statistical test.

Numpy 1.15
```
(Pdb) A[0,47],B[0,47]
(-0.00020975265942979604, -0.00020971624097825795)
```
Numpy 1.14 gave the exact same answer for A and B.
```
(Pdb) A[0,47],B[0,47]
(-0.00020971624097825795, -0.00020971624097825795)
```

It seems to be a precision issue.

**Comment by doutriaux1** [comment]
Should we forward this to numpy people? In the mean time can we play on atol/rtol to make this pass? It seems close enough.

**Comment by dnadeau4** [comment]
I looked a little deeper and one variable is changed from float32 to float64.  If I set atol then in pass, but I want to investigate a little more.  I read the release and they changed something in "ufunc", but nothing related to this.

**Comment by dnadeau4** [comment]
After investigation, I found the issue.  
The new way numpy create their masked array send the code to different areas for "mean".
The results are "double floating" point instead of "single floating" point.  The code use "sum/count" with numpy 1.15 and call some "mean" object in numpy 1.14 due to the `_mask` not being detected the same way. 

https://github.com/numpy/numpy/blob/master/numpy/ma/core.py#L5155-L5160

I will create a issue in the numpy repository
**numpy 1.15**
```python
x = x - xmean
(Pdb) xmean
masked_array(data=[13.800759617286392, 13.947294983682752,
                   14.146195423753955, 14.284184323081487,
                   14.364891341969937, 14.423645792128164,
...
                   13.619312141515032, 13.724408499802216,
                   13.800759617286392],

             mask=[False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
                   False, False, False, False, False, False, False, False,
...
                   False, False, False, False, False, False, False, False,
                   False],
       fill_value=1e+20)

```
**numpy 1.14**
```python
x = x - xmean
(Pdb) xmean
masked_array(data=[13.800759 , 13.947295 , 
                   14.146195 , 14.284184 ,
                   14.364891 , 14.423646 
      
                  13.619312 , 13.724408 ,
                   13.800759 ],

             mask=False,
       fill_value=1e+20,
            dtype=float32)

```

**Comment by durack1** [comment]
@dnadeau4 nice detective work!!
